wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1672662786.610698
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 19
      - 23
      4: 3.9.15
      5: 0.13.6
      8:
      - 5
beta1:
  desc: null
  value: 0.0
beta2:
  desc: null
  value: 0.9
latent_dim:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0002
model_dir:
  desc: null
  value: saved_models/cifar10-256-basic-l2b1final
